### ISSUE TITLE
PoC: service worker + phaser.js

### ISSUE THREAD

**Issue by flockonus** [flockonus/age-of-code#1]
The idea is to have inputs sent from processes that run isolated using service workers or maybe fallback to iframes. Also, the world state will be exported to the worker, so it can figure out its next outputs.

Required
- [x] create a base phaser.js game with 2 "teams" and collidable projectiles
- [x] create a way to load 2 arbitrary service workers from JS #2 

It's to be confirmed whether:
- [x] the worker don't have too much freedom to interfere with the main process - it should only pass messages - **i'm assuming jailed lib is doing a good job, but it's possible not**
- [x] the passing of state will be timely back and forth
- [x] if it's possible to run 2 CPU intensive workers in a CPU with 4 cores, while game render smooth

**Comment by flockonus** [comment]
Considering this experiment done :D
